name: messenger
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
      sdk: flutter

  cupertino_icons: ^1.0.8

  get: ^4.7.2
  flutter_svg: ^2.2.1
  google_fonts: ^6.3.2
  logger: ^2.6.2
  adaptive_dialog: ^2.5.0

  rinf: ^8.7.2
  path_provider: ^2.1.5
  tuple: ^2.0.2
  flutter_web_auth_2: ^5.0.0-alpha.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/tmp/

rinf:
  gen_input_crates:
    - hub
    - matrix-sdk-rinf
  gen_output_dir: lib/src/bindings
