import 'package:messenger/src/bindings/bindings.dart';

RoomInfo mockRoomInfo({String? displayName}) => RoomInfo(
  id: "",
  isDirect: false,
  isSpace: false,
  isFavourite: false,
  alternativeAliases: [],
  membership: Membership.joined,
  heroes: [],
  activeMembersCount: Uint64(BigInt.from(0)),
  invitedMembersCount: Uint64(BigInt.from(0)),
  joinedMembersCount: Uint64(BigInt.from(0)),
  highlightCount: Uint64(BigInt.from(0)),
  notificationCount: Uint64(BigInt.from(0)),
  hasRoomCall: false,
  activeRoomCallParticipants: [],
  isMarkedUnread: false,
  numUnreadMessages: Uint64(BigInt.from(0)),
  numUnreadNotifications: Uint64(BigInt.from(0)),
  numUnreadMentions: Uint64(BigInt.from(0)),
  pinnedEventIds: [],
  historyVisibility: RoomHistoryVisibilityJoined(),
  displayName: displayName,
);
